spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: sdkim
      password: kimsd
      database: admin
      # uri: mongodb: //localhost/test
